version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "buildspec live: preparing artifact for CPC Manager API"
  pre_build:
    commands:
      - rm -rf output || true
      - mkdir -p output
  build:
    commands:
      - rsync -av --exclude='.git' api/ output/api/
      - cp appspec-live.yml output/appspec.yml
      - mkdir -p output/scripts
      - rsync -av --exclude='.git' scripts/* output/scripts/ || true
artifacts:
  files:
    - '**/*'
  base-directory: output
