version: 0.2

phases:
  install:
    commands:
      - echo "buildspec dev: preparing artifact for CPC Manager API"

  pre_build:
    commands:
      - rm -rf output || true
      - mkdir -p output

  build:
    commands:
      - rsync -av --exclude='.git' api/ output/api/
      - cp appspec-dev.yml output/appspec.yml
      - mkdir -p output/scripts
      - rsync -av --exclude='.git' scripts/* output/scripts/ || true

artifacts:
  base-directory: output
  files:
    - '**/*'
